### ISSUE TITLE
"ERROR: No application configured, nothing to run" when running `heroku local`

### ISSUE THREAD

**Issue by LimeBlast** [kvokka/onotole#2]
When I run `heroku local` on a freshly generated project, I get the following error:

```
$ heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
4:38:12 PM web.1    |  [73648] Puma starting in cluster mode...
4:38:12 PM web.1    |  [73648] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
4:38:12 PM web.1    |  [73648] * Min threads: 2, max threads: 16
4:38:12 PM web.1    |  [73648] * Environment: development
4:38:12 PM web.1    |  [73648] * Process workers: 1
4:38:12 PM web.1    |  [73648] * Preloading application
4:38:12 PM web.1    |  [73648] ERROR: No application configured, nothing to run
[DONE] Killing all processes with signal  null
4:38:12 PM web.1    Exited with exit code 1
4:38:12 PM worker.1 |  rake aborted!
4:38:12 PM worker.1 |  SignalException: SIGTERM
4:38:12 PM worker.1 |  /Users/Daniel/Workspace/projecttwo/config/application.rb:3:in `require'
4:38:12 PM worker.1 |  /Users/Daniel/Workspace/projecttwo/config/application.rb:3:in `<top (required)>'
4:38:12 PM worker.1 |  /Users/Daniel/Workspace/projecttwo/Rakefile:5:in `require_relative'
4:38:12 PM worker.1 |  /Users/Daniel/Workspace/projecttwo/Rakefile:5:in `<top (required)>'
4:38:12 PM worker.1 |  /Users/Daniel/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
4:38:12 PM worker.1 |  /Users/Daniel/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
4:38:12 PM worker.1 |  (See full trace by running task with --trace)
4:38:12 PM worker.1 Exited with exit code 1
```

Running `rails server` seems to work just fine.

**Comment by kvokka** [comment]
Hello.
Thank you!
I've made fix for it in last version
You'll need rebuild the app or fix Procfile manual (you'll see the example in templates folder of this repo)
